services:
  server:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 40M